project:
  type: book

lang: ja

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
  pdf:
    pdf-engine: lualatex
    documentclass: ltjbook
    toc: true
    toc-depth: 1

bibliography: references.bib

book:
  title: "オペレーションズ・リサーチ"
  subtitle: "Operations Research: Models, Algorithms, and Implementations"
  # cover-image: cover.png
  # cover-image-alt: |
  #   Alternative text describing the book cover 
  author: 
    - name: "劉子昂"
      id: liuziang
      orcid: 0000-0002-1364-3502
      url: "https://zi-ang-liu.github.io"
      affiliation: 
      - name: 法政大学
        department: 経営システム工学科
  date: today
  page-footer: 
    border: true
    center: "Copyright 2025, Ziang Liu"
  search: true
  twitter-card: true
  site-url: https://zi-ang-liu.github.io/or-book/
  repo-url: https://github.com/zi-ang-liu/or-book
  chapters:
    - index.qmd
    - course-info.qmd
    - notation.qmd
    - part: "在庫モデル"
      chapters:
        - inventory/intro.qmd
        - inventory/eoq.qmd
        - inventory/safety.qmd
        - inventory/wagner-whitin.qmd
        - inventory/newsvendor.qmd
        - inventory/summary.qmd
    - part: "多基準意思決定分析"
      chapters:
        - mcda/ahp.qmd
    - part: "ネットワーク最適化"
      chapters:
        - network/graph.qmd
        # - network/shortest-path.qmd
    - part: "PERT/CPM"
      chapters:
        - pert/project.qmd
        - pert/uncertain.qmd
        - pert/tradeoff.qmd
    - part: "データ包絡分析"
      chapters:
        - dea/intro.qmd
        - dea/ccr.qmd
    - part: "動的計画法"
      chapters:
        - dp/intro.qmd
    - part: "待ち行列理論"
      chapters:
        - queuing/intro.qmd
        - queuing/poisson_process.qmd
        - queuing/birth-death.qmd
    - part: "OR キャリア"
      chapters:
        - career/intro.qmd
    - references.qmd
  appendices:
    - appendices/calculus.qmd
    - appendices/probability.qmd
    - appendices/standard_normal_table.qmd
    - appendices/linear_algebra.qmd
    - appendices/opt_problems.qmd




